# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [9.x, 10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_USER }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      JWT_SUB: ${{ secrets.JWT_SUB }}
      JWT_KEYPASS: ${{ secrets.JWT_KEYPASS }}
      JWT_ISS: ${{ secrets.JWT_ISS }}
      JWT_AUD: ${{ secrets.JWT_AUD }}
      JWT_ALG: ${{ secrets.JWT_ALG }}
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm install
        
    - name: Generate build
      run: npm run build --if-present
    
    - name: Run tests
      run: npm run test:development
      continue-on-error: true

    - name: Run lint
      run: npm run lint
      continue-on-error: true
